from flask import Flask
from flask_mysqldb import MySQL

## __name__ is the name of the module. When running directly from python, it will be '__main__'
app = Flask(__name__)

## configuration of database

app.config["MYSQL_USER"] = 'root'
app.config["MYSQL_PASSWORD"] = 'root'
app.config["MYSQL_DB"] = 'demo'
app.config["MYSQL_HOST"] = 'localhost'
app.config["SECRET_KEY"] = 'key'
app.config['WTF_CSRF_SECRET_KEY'] = 'key'
## secret keys can be generated by secrets.token_hex()

## initialize database connection object
db = MySQL(app)

## routes must be imported after the app object has been initialized
from flaskr import routes
