from flask import Flask
from flask_mysqldb import MySQL

## __name__ is the name of the module. When running directly from python, it will be '__main__'
app = Flask(__name__)

## configuration of database

app.config["MYSQL_USER"] = ''
app.config["MYSQL_PASSWORD"] = ''
app.config["MYSQL_DB"] = ''
app.config["MYSQL_HOST"] = ''
app.config["SECRET_KEY"] = ''
app.config["WTF_CSRF_SECRET_KEY"] = ''
## secret keys can be generated by secrets.token_hex()

## initialize database connection object
db = MySQL(app)

## routes must be imported after the app object has been initialized
from dbdemo import routes
